/**
 * Seed Template Bundles for Local Workspace
 *
 * Re-exports the seed templates. This file exists in the workspace package
 * so the local API route can import it without reaching into the Next.js src/.
 */

// We duplicate the essential data here to avoid cross-package imports.
// The canonical source is src/lib/templates/seed-templates.ts in the web app.

export const SEED_TEMPLATES = [
  {
    slug: 'lead-qualification-pipeline',
    name: 'Lead Qualification Pipeline',
    description: 'Automatically qualify inbound leads, save contacts, and notify your team.',
    long_description: 'When a new lead comes in via webhook, this bundle qualifies them using AI, saves the contact to your CRM, and sends a notification.',
    icon: 'Magnet',
    category: 'lead_gen',
    business_types: ['saas_startup', 'agency', 'consulting'],
    tags: ['leads', 'qualification', 'webhook', 'contacts'],
    difficulty: 'beginner',
    featured: true,
    sort_order: 1,
    agents: [{ ref_id: 'lead_qualifier', name: '{{company_name}} Lead Qualifier', role: 'Lead Qualification Specialist', description: 'Analyzes inbound leads and scores them.', system_prompt: 'You are a lead qualification specialist for {{company_name}}.', department: 'Sales', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 1024, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'lead_qualification_flow', name: 'Lead Qualification Flow', description: 'Webhook triggers lead qualification.', trigger_type: 'webhook', trigger_config: {}, steps: [{ id: 'step_qualify', step_type: 'agent_prompt', label: 'Qualify Lead', agent_ref: 'lead_qualifier', prompt: 'Qualify this incoming lead.' }, { id: 'step_save', step_type: 'save_contact', label: 'Save Contact' }, { id: 'step_notify', step_type: 'send_notification', label: 'Notify Team' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'industry', label: 'Target Industry', description: 'Industry you serve', type: 'text', required: false, default_value: 'technology' }, { key: 'notification_channel', label: 'Notification Channel', description: 'Where to send notifications', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }, { label: 'None', value: 'none' }] }],
  },
  {
    slug: 'content-repurposing-engine',
    name: 'Content Repurposing Engine',
    description: 'Turn one topic into a blog post and social media content weekly.',
    long_description: 'Every week, generate a blog post and split it into social media posts.',
    icon: 'PencilLine',
    category: 'content',
    business_types: [],
    tags: ['content', 'social media', 'blog', 'schedule'],
    difficulty: 'beginner',
    featured: true,
    sort_order: 2,
    agents: [{ ref_id: 'content_writer', name: '{{company_name}} Content Writer', role: 'Content Writer', description: 'Writes blog posts.', system_prompt: 'You are a content writer for {{company_name}}.', department: 'Marketing', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, max_tokens: 4096, approval_required: false, browser_enabled: false } }, { ref_id: 'social_media_manager', name: '{{company_name}} Social Media Manager', role: 'Social Media Manager', description: 'Creates social posts.', system_prompt: 'You are a social media manager for {{company_name}}.', department: 'Marketing', tools: [], config: { model: 'claude-sonnet-4-20250514', temperature: 0.8, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'weekly_content_flow', name: 'Weekly Content Pipeline', description: 'Weekly blog + social content.', trigger_type: 'schedule', trigger_config: { cron: '0 9 * * 1' }, steps: [{ id: 'step_write', step_type: 'agent_prompt', label: 'Write Blog Post', agent_ref: 'content_writer' }, { id: 'step_social', step_type: 'agent_prompt', label: 'Create Social Posts', agent_ref: 'social_media_manager' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'target_audience', label: 'Target Audience', description: 'Who your content is for', type: 'text', required: true }],
  },
  {
    slug: 'customer-support-triage',
    name: 'Customer Support Triage',
    description: 'Classify support requests by urgency and draft responses.',
    long_description: 'Classify urgency, draft responses, notify for critical issues.',
    icon: 'Headset',
    category: 'support',
    business_types: ['saas_startup', 'ecommerce'],
    tags: ['support', 'triage', 'webhook'],
    difficulty: 'beginner',
    featured: false,
    sort_order: 3,
    agents: [{ ref_id: 'support_triage', name: '{{company_name}} Support Triage', role: 'Support Triage Specialist', description: 'Classifies support tickets.', system_prompt: 'You are a support triage specialist for {{company_name}}.', department: 'Support', tools: [], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 1024, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'support_triage_flow', name: 'Support Triage Flow', description: 'Classify and respond to support requests.', trigger_type: 'webhook', trigger_config: {}, steps: [{ id: 'step_triage', step_type: 'agent_prompt', label: 'Triage Request', agent_ref: 'support_triage' }, { id: 'step_notify', step_type: 'send_notification', label: 'Notify Team' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'Where to send notifications', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }, { label: 'None', value: 'none' }] }],
  },
  {
    slug: 'weekly-business-briefing',
    name: 'Weekly Business Briefing',
    description: 'Get a weekly summary of key metrics and insights every Monday.',
    long_description: 'A Data Analyst reviews activity and generates a concise briefing.',
    icon: 'ChartBar',
    category: 'analytics',
    business_types: [],
    tags: ['analytics', 'briefing', 'weekly', 'schedule'],
    difficulty: 'beginner',
    featured: true,
    sort_order: 4,
    agents: [{ ref_id: 'data_analyst', name: '{{company_name}} Data Analyst', role: 'Data Analyst', description: 'Analyzes metrics and generates briefings.', system_prompt: 'You are a data analyst for {{company_name}}.', department: 'Operations', tools: [], config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'weekly_briefing_flow', name: 'Weekly Briefing', description: 'Weekly business briefing.', trigger_type: 'schedule', trigger_config: { cron: '0 8 * * 1' }, steps: [{ id: 'step_analyze', step_type: 'agent_prompt', label: 'Generate Briefing', agent_ref: 'data_analyst' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Briefing' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'industry', label: 'Industry', description: 'Your industry', type: 'text', required: false, default_value: 'technology' }, { key: 'notification_channel', label: 'Delivery Channel', description: 'Where to send the briefing', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }] }],
  },
  {
    slug: 'form-to-crm-pipeline',
    name: 'Form to CRM Pipeline',
    description: 'When a site form is submitted, save the contact and qualify the lead.',
    long_description: 'Connects site forms to your contact pipeline.',
    icon: 'Magnet',
    category: 'lead_gen',
    business_types: [],
    tags: ['forms', 'crm', 'contacts', 'leads'],
    difficulty: 'beginner',
    featured: false,
    sort_order: 5,
    agents: [{ ref_id: 'lead_qualifier', name: '{{company_name}} Lead Qualifier', role: 'Lead Qualification Specialist', description: 'Scores form submissions.', system_prompt: 'You are a lead qualifier for {{company_name}}.', department: 'Sales', tools: [], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 512, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'form_to_crm_flow', name: 'Form to CRM Pipeline', description: 'Save form submissions and qualify.', trigger_type: 'event', trigger_config: { event_type: 'page_form_submit' }, steps: [{ id: 'step_save', step_type: 'save_contact', label: 'Save Contact' }, { id: 'step_qualify', step_type: 'agent_prompt', label: 'Qualify Lead', agent_ref: 'lead_qualifier' }, { id: 'step_notify', step_type: 'send_notification', label: 'Notify Team' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'Where to send notifications', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }, { label: 'None', value: 'none' }] }],
  },
  {
    slug: 'contact-enrichment-pipeline',
    name: 'Contact Enrichment Pipeline',
    description: 'Automatically research and enrich new contacts.',
    long_description: 'When a new contact is added, research their company info and social profiles.',
    icon: 'GearSix',
    category: 'operations',
    business_types: ['saas_startup', 'agency'],
    tags: ['contacts', 'enrichment', 'research'],
    difficulty: 'intermediate',
    featured: false,
    sort_order: 6,
    agents: [{ ref_id: 'lead_researcher', name: '{{company_name}} Lead Researcher', role: 'Lead Researcher', description: 'Researches contacts.', system_prompt: 'You are a lead researcher for {{company_name}}.', department: 'Sales', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 1024, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'contact_enrichment_flow', name: 'Contact Enrichment Flow', description: 'Research and enrich new contacts.', trigger_type: 'event', trigger_config: { event_type: 'contact_created' }, steps: [{ id: 'step_research', step_type: 'agent_prompt', label: 'Research Contact', agent_ref: 'lead_researcher' }, { id: 'step_update', step_type: 'update_contact', label: 'Update Contact' }], cooldown_seconds: 300 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }],
  },
  {
    slug: 'service-order-pipeline',
    name: 'Service Order Pipeline',
    description: 'Automate service delivery from intake form to invoicing. When a client submits a service request, an agent analyzes requirements, executes the work, generates an invoice, and emails the client.',
    long_description: 'End-to-end service delivery automation. A form submission triggers the pipeline: save the client as a contact, have an AI agent analyze requirements and generate a scope of work, create an invoice for the service, email the client with the deliverable and invoice, and log the event on their contact record.',
    icon: 'Handshake',
    category: 'sales',
    business_types: ['agency', 'consulting', 'service_business'],
    tags: ['service', 'invoicing', 'delivery', 'forms', 'pipeline'],
    difficulty: 'intermediate',
    featured: false,
    sort_order: 7,
    agents: [{ ref_id: 'service_delivery_agent', name: '{{company_name}} Service Delivery Agent', role: 'Service Delivery Specialist', description: 'Analyzes client requirements and executes service delivery.', system_prompt: 'You are a service delivery specialist for {{company_name}}. Analyze requirements, determine scope, estimate effort, and generate a clear scope document.', department: 'Operations', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'service_order_flow', name: 'Service Order Pipeline', description: 'From form submission to invoicing and delivery.', trigger_type: 'event', trigger_config: { event_type: 'page_form_submit' }, steps: [{ id: 'step_save_contact', step_type: 'save_contact', label: 'Save Client Contact' }, { id: 'step_analyze', step_type: 'agent_prompt', label: 'Analyze Requirements', agent_ref: 'service_delivery_agent' }, { id: 'step_invoice', step_type: 'generate_invoice', label: 'Generate Invoice' }, { id: 'step_notify_client', step_type: 'send_notification', label: 'Email Client' }, { id: 'step_log_event', step_type: 'log_contact_event', label: 'Log Delivery' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'service_name', label: 'Service Name', description: 'The name of the service you deliver', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'How to notify clients about their order', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }, { label: 'None', value: 'none' }] }],
  },
  {
    slug: 'quote-to-delivery',
    name: 'Quote to Delivery Pipeline',
    description: 'Generate quotes from client inquiries, send proposals, and deliver services with automatic invoicing once approved.',
    long_description: 'A two-phase sales and delivery pipeline. Phase one: when a client inquiry arrives via form, an AI agent generates a detailed quote with pricing and emails the proposal. Phase two: after approval, the agent executes the service, generates an invoice, and delivers the final result.',
    icon: 'Handshake',
    category: 'sales',
    business_types: ['agency', 'consulting', 'freelancer', 'service_business'],
    tags: ['quotes', 'proposals', 'delivery', 'invoicing', 'forms', 'sales'],
    difficulty: 'intermediate',
    featured: false,
    sort_order: 8,
    agents: [{ ref_id: 'proposal_delivery_agent', name: '{{company_name}} Proposal & Delivery Agent', role: 'Proposal & Delivery Specialist', description: 'Generates quotes from inquiries and manages service delivery.', system_prompt: 'You are a proposal and delivery specialist for {{company_name}}. Generate quotes with line items and pricing from client inquiries, and execute services after approval.', department: 'Sales', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'quote_to_delivery_flow', name: 'Quote to Delivery Pipeline', description: 'Generate a quote, send the proposal, deliver the service, and invoice.', trigger_type: 'event', trigger_config: { event_type: 'page_form_submit' }, steps: [{ id: 'step_save_contact', step_type: 'save_contact', label: 'Save Client Contact' }, { id: 'step_generate_quote', step_type: 'agent_prompt', label: 'Generate Quote', agent_ref: 'proposal_delivery_agent' }, { id: 'step_send_proposal', step_type: 'send_notification', label: 'Send Proposal' }, { id: 'step_execute_service', step_type: 'agent_prompt', label: 'Execute Service', agent_ref: 'proposal_delivery_agent' }, { id: 'step_invoice', step_type: 'generate_invoice', label: 'Generate Invoice' }, { id: 'step_deliver', step_type: 'send_notification', label: 'Deliver Results' }], cooldown_seconds: 0 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'How to send proposals and deliverables to clients', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }, { label: 'None', value: 'none' }] }],
  },
  {
    slug: 'monthly-client-billing',
    name: 'Monthly Client Billing',
    description: 'Automatically generate and send monthly invoices to active clients. Runs on the 1st of each month, gathers deliverables, and sends a revenue summary.',
    long_description: 'A scheduled billing pipeline that runs on the 1st of every month at 9 AM. A Billing Agent reviews the past month\'s deliverables for each active client, generates invoices, and emails them along with a monthly revenue summary for your team.',
    icon: 'CurrencyDollar',
    category: 'operations',
    business_types: ['agency', 'consulting', 'freelancer', 'service_business'],
    tags: ['billing', 'invoicing', 'monthly', 'schedule', 'finance'],
    difficulty: 'intermediate',
    featured: false,
    sort_order: 9,
    agents: [{ ref_id: 'billing_agent', name: '{{company_name}} Billing Agent', role: 'Billing Specialist', description: 'Gathers monthly deliverables and generates invoices for active clients.', system_prompt: 'You are a billing specialist for {{company_name}}. Review the past month\'s deliverables for each active client, compile line items, calculate totals, and generate a monthly revenue summary.', department: 'Finance', tools: [], config: { model: 'claude-sonnet-4-20250514', temperature: 0.2, max_tokens: 4096, approval_required: false, browser_enabled: false } }],
    automations: [{ ref_id: 'monthly_billing_flow', name: 'Monthly Client Billing', description: 'Generate and send monthly invoices on the 1st of each month.', trigger_type: 'schedule', trigger_config: { cron: '0 9 1 * *' }, steps: [{ id: 'step_gather', step_type: 'agent_prompt', label: 'Gather Deliverables', agent_ref: 'billing_agent' }, { id: 'step_invoice', step_type: 'generate_invoice', label: 'Generate Invoices' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Invoices and Summary' }], cooldown_seconds: 3600 }],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'Where to send invoices and the monthly summary', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }] }],
  },
  {
    slug: 'github-ops-pipeline',
    name: 'GitHub Ops Pipeline',
    description: 'Daily GitHub digest and automatic issue triage for your repos.',
    long_description: 'A Repo Ops agent monitors your GitHub repos daily, summarizing what shipped, what is blocked, and what needs attention. New issues are automatically triaged and added to your board.',
    icon: 'GitBranch',
    category: 'operations',
    business_types: ['tech_company', 'saas_startup'],
    tags: ['github', 'engineering', 'triage', 'daily digest'],
    difficulty: 'beginner',
    featured: true,
    sort_order: 10,
    agents: [{ ref_id: 'repo_ops_agent', name: '{{company_name}} Repo Ops', role: 'GitHub Activity Summarizer', description: 'Summarizes GitHub activity and triages issues.', system_prompt: 'You are a Repo Ops agent for {{company_name}}. Summarize GitHub activity across {{github_repos}}. Flag stale PRs, failing CI, and unassigned issues. Triage new issues by priority.', department: 'Engineering', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [
      { ref_id: 'daily_github_digest', name: 'Daily GitHub Digest', description: 'Weekday morning summary of GitHub activity.', trigger_type: 'schedule', trigger_config: { cron: '0 9 * * 1-5' }, steps: [{ id: 'step_summarize', step_type: 'agent_prompt', label: 'Summarize Activity', agent_ref: 'repo_ops_agent', prompt: 'Summarize yesterday\'s GitHub activity across {{github_repos}}. What shipped, what is blocked, what needs attention.' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Digest' }], cooldown_seconds: 0 },
      { ref_id: 'issue_triage', name: 'Issue Triage', description: 'Automatically triage new GitHub issues.', trigger_type: 'webhook', trigger_config: {}, steps: [{ id: 'step_classify', step_type: 'agent_prompt', label: 'Classify Issue', agent_ref: 'repo_ops_agent', prompt: 'Triage this GitHub issue. Classify priority P0-P3, suggest labels and assignee.' }, { id: 'step_task', step_type: 'create_task', label: 'Add to Board' }], cooldown_seconds: 0 },
    ],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'github_repos', label: 'GitHub Repos', description: 'Comma-separated list of repos to monitor (e.g. org/repo1, org/repo2)', type: 'text', required: true }, { key: 'notification_channel', label: 'Notification Channel', description: 'Where to send the daily digest', type: 'select', required: true, default_value: 'email', options: [{ label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }] }],
  },
  {
    slug: 'developer-content-engine',
    name: 'Developer Content Engine',
    description: 'Weekly changelogs and technical blog posts, written automatically.',
    long_description: 'A Developer Content agent writes a weekly changelog from merged PRs every Monday and drafts a technical blog post every Wednesday. A Release Notes agent is available for on-demand release note generation.',
    icon: 'PencilLine',
    category: 'content',
    business_types: ['tech_company', 'saas_startup'],
    tags: ['changelog', 'blog', 'developer content', 'release notes'],
    difficulty: 'beginner',
    featured: true,
    sort_order: 11,
    agents: [
      { ref_id: 'dev_content_agent', name: '{{company_name}} Developer Content', role: 'Technical Content Writer', description: 'Writes changelogs and technical blog posts.', system_prompt: 'You are a Developer Content agent for {{company_name}}. Write technical content for {{target_audience}}. Create changelogs from merged PRs and technical blog posts. Tone: direct, technical, no marketing fluff.', department: 'Marketing', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, max_tokens: 4096, approval_required: false, browser_enabled: false } },
      { ref_id: 'release_notes_agent', name: '{{company_name}} Release Notes', role: 'User-Facing Release Writer', description: 'Writes user-facing release notes from PRs and commits.', system_prompt: 'You are a Release Notes agent for {{company_name}}. Write clear, user-facing release notes for {{product_name}}. Categorize: features, fixes, breaking changes. Keep entries scannable.', department: 'Engineering', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, max_tokens: 2048, approval_required: false, browser_enabled: false } },
    ],
    automations: [
      { ref_id: 'weekly_changelog', name: 'Weekly Changelog', description: 'Monday morning changelog from the past week.', trigger_type: 'schedule', trigger_config: { cron: '0 10 * * 1' }, steps: [{ id: 'step_write', step_type: 'agent_prompt', label: 'Write Changelog', agent_ref: 'dev_content_agent', prompt: 'Write a changelog for the past week for {{product_name}}. Categorize: features, fixes, improvements, breaking changes.' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Changelog' }], cooldown_seconds: 0 },
      { ref_id: 'blog_draft', name: 'Blog Draft', description: 'Wednesday morning technical blog post draft.', trigger_type: 'schedule', trigger_config: { cron: '0 9 * * 3' }, steps: [{ id: 'step_draft', step_type: 'agent_prompt', label: 'Draft Blog Post', agent_ref: 'dev_content_agent', prompt: 'Draft a technical blog post for {{target_audience}}. Research current trends and write a practical, code-heavy post under 1500 words.' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Draft' }], cooldown_seconds: 0 },
    ],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'product_name', label: 'Product Name', description: 'Your product name', type: 'text', required: true }, { key: 'target_audience', label: 'Target Audience', description: 'Who reads your content (e.g. backend developers, DevOps engineers)', type: 'text', required: true, default_value: 'developers' }],
  },
  {
    slug: 'tech-support-loop',
    name: 'Tech Support Loop',
    description: 'Automatic ticket triage and weekly FAQ pattern analysis.',
    long_description: 'A Support Analyst triages incoming support tickets by urgency and drafts responses. Every Friday, it analyzes the week\'s patterns and suggests documentation improvements.',
    icon: 'Headset',
    category: 'support',
    business_types: ['tech_company', 'saas_startup'],
    tags: ['support', 'triage', 'faq', 'documentation'],
    difficulty: 'beginner',
    featured: false,
    sort_order: 12,
    agents: [{ ref_id: 'support_analyst', name: '{{company_name}} Support Analyst', role: 'Support Triage & Patterns', description: 'Triages support tickets and analyzes weekly patterns.', system_prompt: 'You are a Support Analyst for {{company_name}}. Triage support requests by urgency (P0-P3). Draft responses using {{docs_url}} as reference. Track weekly patterns and suggest documentation improvements.', department: 'Support', tools: ['web_search'], config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, max_tokens: 2048, approval_required: false, browser_enabled: false } }],
    automations: [
      { ref_id: 'ticket_triage', name: 'Ticket Triage', description: 'Automatically triage incoming support tickets.', trigger_type: 'webhook', trigger_config: {}, steps: [{ id: 'step_triage', step_type: 'agent_prompt', label: 'Triage Ticket', agent_ref: 'support_analyst', prompt: 'Triage this support request. Classify urgency P0-P3. Draft a response referencing {{docs_url}}. Flag P0/P1 for escalation.' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Result' }], cooldown_seconds: 0 },
      { ref_id: 'weekly_faq_patterns', name: 'Weekly FAQ Patterns', description: 'Friday analysis of the week\'s support patterns.', trigger_type: 'schedule', trigger_config: { cron: '0 14 * * 5' }, steps: [{ id: 'step_analyze', step_type: 'agent_prompt', label: 'Analyze Patterns', agent_ref: 'support_analyst', prompt: 'Analyze this week\'s support tickets. Top recurring issues, common questions, documentation gaps. Suggest improvements to {{docs_url}}.' }, { id: 'step_notify', step_type: 'send_notification', label: 'Send Report' }], cooldown_seconds: 0 },
    ],
    variables: [{ key: 'company_name', label: 'Company Name', description: 'Your company name', type: 'text', required: true }, { key: 'docs_url', label: 'Documentation URL', description: 'URL of your product documentation', type: 'text', required: true }],
  },
];
