/**
 * X Post Drafts MCP tools
 *
 * ohwow_list_x_drafts — list drafts (optionally filtered by status).
 * ohwow_approve_x_draft(id) — flip status to 'approved'.
 * ohwow_reject_x_draft(id) — flip status to 'rejected'.
 *
 * Drafts are created by the hourly XDraftDistillerScheduler from
 * novel market-radar findings. Operator reviews them here before
 * anything leaves the daemon.
 */

import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { DaemonApiClient } from '../api-client.js';

interface XDraftJson {
  id: string;
  workspace_id: string;
  body: string;
  source_finding_id: string | null;
  status: 'pending' | 'approved' | 'rejected';
  created_at: string;
  approved_at: string | null;
  rejected_at: string | null;
}

function errorResponse(message: string) {
  return {
    content: [{ type: 'text' as const, text: message }],
    isError: true,
  };
}

function jsonResponse(payload: unknown) {
  return {
    content: [{ type: 'text' as const, text: JSON.stringify(payload, null, 2) }],
  };
}

export function registerXDraftTools(server: McpServer, client: DaemonApiClient): void {
  server.tool(
    'ohwow_list_x_drafts',
    "[Market Radar] List candidate X post drafts the process has queued from novel market-radar findings. Each draft is 1-2 tweet-length post bodies, generated by the hourly XDraftDistillerScheduler from insights whose subject starts with `market:` (competitor pricing, rival releases, arXiv / HN / PH drift). Rows are 'pending' until you approve or reject; once approved, the posting path picks them up. Use status='pending' to see only what's waiting for you. Each row carries the source_finding_id so you can trace it back with ohwow_list_findings.",
    {
      status: z
        .enum(['pending', 'approved', 'rejected'])
        .optional()
        .describe("Filter by status. Default returns all. Use 'pending' to see only what needs review."),
      limit: z
        .number()
        .int()
        .positive()
        .max(200)
        .optional()
        .describe('Cap on rows returned. Default 50, hard max 200.'),
    },
    async ({ status, limit }) => {
      try {
        const qs = new URLSearchParams();
        if (status) qs.set('status', status);
        if (limit !== undefined) qs.set('limit', String(limit));
        const qsStr = qs.toString() ? `?${qs.toString()}` : '';
        const result = (await client.get(`/api/x-drafts${qsStr}`)) as {
          data?: XDraftJson[];
          count?: number;
          limit?: number;
          error?: string;
        };
        if (result.error) return errorResponse(`Couldn't list X drafts: ${result.error}`);
        const drafts = result.data ?? [];
        return jsonResponse({
          ok: true,
          count: drafts.length,
          limit: result.limit,
          drafts,
          note:
            drafts.length === 0
              ? 'No drafts queued. Either the market-radar distiller has not ticked yet, or no insights have crossed the novelty floor. Run ohwow_list_insights to see what is ranked.'
              : `${drafts.length} draft(s). Approve with ohwow_approve_x_draft, reject with ohwow_reject_x_draft. Trace back with ohwow_list_findings { experiment_id: <from source_finding_id> }.`,
        });
      } catch (err) {
        return errorResponse(`Error: ${err instanceof Error ? err.message : 'Unknown error'}`);
      }
    },
  );

  server.tool(
    'ohwow_approve_x_draft',
    "[Market Radar] Approve an X post draft. Flips status to 'approved' and stamps approved_at. The posting path picks approved drafts up on its next cadence tick. Approval is reversible only by the draft never being picked up — once it posts, the posted_log is the source of truth.",
    {
      id: z
        .string()
        .min(1)
        .describe('The draft row id from ohwow_list_x_drafts.'),
    },
    async ({ id }) => {
      try {
        const result = (await client.post(`/api/x-drafts/${encodeURIComponent(id)}/approve`, {})) as {
          data?: XDraftJson;
          error?: string;
        };
        if (result.error) return errorResponse(`Couldn't approve draft: ${result.error}`);
        if (!result.data) return errorResponse('Draft not found.');
        return jsonResponse({ ok: true, draft: result.data });
      } catch (err) {
        return errorResponse(`Error: ${err instanceof Error ? err.message : 'Unknown error'}`);
      }
    },
  );

  server.tool(
    'ohwow_reject_x_draft',
    "[Market Radar] Reject an X post draft. Flips status to 'rejected' and stamps rejected_at. Rejected drafts are skipped by the posting path and remain in the table for audit.",
    {
      id: z
        .string()
        .min(1)
        .describe('The draft row id from ohwow_list_x_drafts.'),
    },
    async ({ id }) => {
      try {
        const result = (await client.post(`/api/x-drafts/${encodeURIComponent(id)}/reject`, {})) as {
          data?: XDraftJson;
          error?: string;
        };
        if (result.error) return errorResponse(`Couldn't reject draft: ${result.error}`);
        if (!result.data) return errorResponse('Draft not found.');
        return jsonResponse({ ok: true, draft: result.data });
      } catch (err) {
        return errorResponse(`Error: ${err instanceof Error ? err.message : 'Unknown error'}`);
      }
    },
  );
}
