/**
 * MCP Server Catalog
 * Curated list of popular MCP servers with pre-configured settings.
 */

export interface McpCatalogEntry {
  id: string;
  name: string;
  description: string;
  transport: 'stdio' | 'http';
  command: string;
  args: string[];
  envVarsRequired: Array<{ key: string; label: string }>;
  category: 'files' | 'databases' | 'apis' | 'development' | 'communication' | 'productivity' | 'media' | 'cms' | 'integrations';
}

export const MCP_SERVER_CATALOG: McpCatalogEntry[] = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read, write, and search files on your machine',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/tmp'],
    envVarsRequired: [],
    category: 'files',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Manage repos, issues, and pull requests',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    envVarsRequired: [{ key: 'GITHUB_PERSONAL_ACCESS_TOKEN', label: 'GitHub token' }],
    category: 'development',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Read and send Slack messages',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    envVarsRequired: [
      { key: 'SLACK_BOT_TOKEN', label: 'Slack bot token' },
      { key: 'SLACK_TEAM_ID', label: 'Slack team ID' },
    ],
    category: 'communication',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query and explore PostgreSQL databases',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    envVarsRequired: [{ key: 'POSTGRES_CONNECTION_STRING', label: 'Connection string' }],
    category: 'databases',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and explore SQLite databases',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite'],
    envVarsRequired: [{ key: 'SQLITE_DB_PATH', label: 'Database file path' }],
    category: 'databases',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Search the web with Brave',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    envVarsRequired: [{ key: 'BRAVE_API_KEY', label: 'Brave API key' }],
    category: 'apis',
  },
  {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch and read web pages and APIs',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    envVarsRequired: [],
    category: 'apis',
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Persistent knowledge graph for storing and retrieving information',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    envVarsRequired: [],
    category: 'development',
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    description: 'Search places, get directions, and geocode addresses',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-google-maps'],
    envVarsRequired: [{ key: 'GOOGLE_MAPS_API_KEY', label: 'Google Maps API key' }],
    category: 'apis',
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Think through problems step by step',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    envVarsRequired: [],
    category: 'development',
  },
  {
    id: 'everything',
    name: 'Everything (Demo)',
    description: 'Demo server with sample tools for testing',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    envVarsRequired: [],
    category: 'development',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Browser automation and web scraping',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    envVarsRequired: [],
    category: 'development',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Browser automation with Playwright',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-playwright'],
    envVarsRequired: [],
    category: 'development',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Search and analyze error reports from Sentry',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@sentry/mcp-server-sentry'],
    envVarsRequired: [{ key: 'SENTRY_AUTH_TOKEN', label: 'Sentry auth token' }],
    category: 'development',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Search and manage files in Google Drive',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gdrive'],
    envVarsRequired: [{ key: 'GDRIVE_CREDENTIALS_PATH', label: 'Google credentials JSON path' }],
    category: 'files',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Read and search notes in your Obsidian vault',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-obsidian'],
    envVarsRequired: [{ key: 'OBSIDIAN_VAULT_PATH', label: 'Vault path' }],
    category: 'files',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Query and manage MySQL databases',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@benborla29/mcp-server-mysql'],
    envVarsRequired: [{ key: 'MYSQL_CONNECTION_STRING', label: 'Connection string' }],
    category: 'databases',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Manage payments, subscriptions, and customers',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@stripe/agent-toolkit', '--mcp'],
    envVarsRequired: [{ key: 'STRIPE_SECRET_KEY', label: 'Stripe secret key' }],
    category: 'apis',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage Cloudflare Workers, KV, and DNS',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@cloudflare/mcp-server-cloudflare'],
    envVarsRequired: [{ key: 'CLOUDFLARE_API_TOKEN', label: 'Cloudflare API token' }],
    category: 'apis',
  },
  {
    id: 'exa',
    name: 'Exa',
    description: 'AI-powered web search and content retrieval',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-exa'],
    envVarsRequired: [{ key: 'EXA_API_KEY', label: 'Exa API key' }],
    category: 'apis',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Manage issues, projects, and cycles in Linear',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-linear'],
    envVarsRequired: [{ key: 'LINEAR_API_KEY', label: 'Linear API key' }],
    category: 'productivity',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Search, read, and create Notion pages and databases',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@notionhq/notion-mcp-server'],
    envVarsRequired: [{ key: 'NOTION_API_KEY', label: 'Notion API key' }],
    category: 'productivity',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Manage tasks and projects in Todoist',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-todoist'],
    envVarsRequired: [{ key: 'TODOIST_API_TOKEN', label: 'Todoist API token' }],
    category: 'productivity',
  },


  // === CMS ===
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Manage WordPress posts, pages, media, categories, tags, comments, and site settings',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-wordpress'],
    envVarsRequired: [
      { key: 'WORDPRESS_SITE_URL', label: 'WordPress site URL' },
      { key: 'WORDPRESS_USERNAME', label: 'WordPress username' },
      { key: 'WORDPRESS_APPLICATION_PASSWORD', label: 'WordPress application password' },
    ],
    category: 'cms',
  },

  // === Media Generation ===
  {
    id: 'fal-ai',
    name: 'Fal.ai',
    description: 'Generate images and videos with Flux, SDXL, and more',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@fal-ai/mcp-server'],
    envVarsRequired: [{ key: 'FAL_KEY', label: 'Fal.ai API key' }],
    category: 'media',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run image, video, and audio models via Replicate',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@replicate/mcp-server'],
    envVarsRequired: [{ key: 'REPLICATE_API_TOKEN', label: 'Replicate API token' }],
    category: 'media',
  },
  {
    id: 'openai-image',
    name: 'OpenAI Images',
    description: 'Generate images with DALL-E and GPT Image',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@openai/mcp-server-images'],
    envVarsRequired: [{ key: 'OPENAI_API_KEY', label: 'OpenAI API key' }],
    category: 'media',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'Generate images, videos, music, voice cloning, and 3D assets',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-minimax'],
    envVarsRequired: [
      { key: 'MINIMAX_API_KEY', label: 'MiniMax API key' },
      { key: 'MINIMAX_GROUP_ID', label: 'MiniMax Group ID' },
    ],
    category: 'media',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech with realistic AI voices',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-elevenlabs'],
    envVarsRequired: [{ key: 'ELEVENLABS_API_KEY', label: 'ElevenLabs API key' }],
    category: 'media',
  },

  // === Integrations ===
  {
    id: 'openclaw',
    name: 'OpenClaw',
    description: 'Run OpenClaw agent skills in a sandboxed environment',
    transport: 'stdio',
    command: 'node',
    args: [],  // Dynamically set by mcp-bridge.ts
    envVarsRequired: [],
    category: 'integrations',
  },
];

export const CATALOG_CATEGORIES = [
  { id: 'productivity', label: 'Productivity' },
  { id: 'development', label: 'Development' },
  { id: 'media', label: 'Media Generation' },
  { id: 'files', label: 'Files' },
  { id: 'databases', label: 'Databases' },
  { id: 'apis', label: 'APIs' },
  { id: 'communication', label: 'Communication' },
  { id: 'cms', label: 'CMS' },
  { id: 'integrations', label: 'Integrations' },
] as const;
